package com.jhonny.SharePointReports.PersistenceModels;

public class Web
{
    
}

/*
    site type,
    site id,
    allowAutomaticASPXPageIndexing,
    allowCreateDeclarativeWorkflowForCurrentUser,
    allowDesignerForCurrentUser,
    allowMasterPageEditingForCurrentUser,
    allowRevertFromTemplateForCurrentUser,
    allowRssFeeds,
    allowSaveDeclarativeWorkflowAsTemplateForCurrentUser,
    allowSavePublishDeclarativeWorkflowForCurrentUser,
    alternateCssUrl,
    appInstanceId,
    associatedOwnerGroup,
    configuration,
    containsConfidentialInfo
    ,DateTime created,
    currentUserInfo,
    customMasterUrldescription,
    designerDownloadUrlForCurrentUser,
    disableAppViews,
    disableFlows,
    documentLibraryCalloutOfficeWebAppPreviewersDisabled,
    enableMinimalDownload,
    excludeFromOfflineClient,
    id,isMultilingual,
    language,
    actualLanguage,
    DateTime 
    lastItemModifiedDate,DateTime 
    lastItemUserModifiedDate,
    masterUrl,membersCanShare,
    noCrawl,
    notificationsInOneDriveForBusinessEnabled,
    notificationsInSharePoEnabled,
    overwriteTranslationsOnChange,
    previewFeaturesEnabled,
    quickLaunchEnabled,
    recycleBinEnabled,
    requestAccessEmail,
    saveSiteAsTemplateEnabled,
    serverRelativeUrl,
    showUrlStructureForCurrentUser,
    siteLogoDescription,
    siteLogoUrl,
    supportedUILanguageIds,
    syndicationEnabled,
    tenantTagPolicyEnabled,
    themedCssFolderUrl,
    thirdPartyMdmEnabled,
    title,
    treeViewEnabled,
    uIVersion,
    uIVersionConfigurationEnabled,
    url,
    webs,
    webTemplate,
    level,
    child,
    immediateChild,
    depth,
    parentId,
    parentUrl,
    parentTitle,
    userCount,
    uniqueInternalUserCount,
    uniqueExternalUserCount,
    externalOwnerCount,
    externalMemberCount,
    externalVisitorCount,
    externalAdminCount,
    externalMembershipCount,
    adminCount,
    ownerCount,
    memberCount,
    visitorCount,
    groupCount,
    listCount,
    documentLibraryCount,
    siteUrl,
    siteTitle,
    hasUniqueRoleAssignments,
    rootWeb,
    inactiveDays,
    associatedMemberGroupAllowMembersEditMembership,
    IsSitePublic,
    availableRetentionLable,
    recycleBinSize,
    useAccessRequestDefault,
    guestUserCount,
    guestUserInvititedByMail,
    annonymousLinkCount,e
    mailAuthenticationGuestUser,
    sharingCapability



 */